### ISSUE TITLE
Fix Memory leak in test-queue.cpp

### ISSUE THREAD

**Issue by Danijj89** [arthurarmani/software-dev-steven-arthur-public#2]
After running the test in valgrind we found out that tests using push() and pop() have memory leaks. The reason is that we assumed push() would create a copy of the element passed in before storing it, thus they need to be freed when popped. We believe that making a copy of the element before storing is important so that we don't have references to the objects from outside the queue class. Examples of these memory leaks are at lines 42, 74, 131,and string s3, s4 in test_pop_element() at lines 88-89. Thanks

**Comment by sbhornjr** [comment]
Hey guys,

I'm a little confused. We completely agree with you about copying elements, we were expecting you to do that in your implementation of our design, so we thought that we were allowing for that. We were under the impression that that would be up to your implementation; we can't do anything in the function headers to enforce copying of elements. This is something that you would do in the constructor.

**Comment by sbhornjr** [comment]
Thinking about it more, would us deleting the Strings that we get from popping in the tests fix the memory errors?

**Comment by Danijj89** [comment]
Yeah, that was what I meant, sorry for the confusion. Each string that gets added into the queue will get copied so the copy has to be freed when popping them off the queue, else that memory block is lost. Thanks for the quick response btw!

**Comment by sbhornjr** [comment]
No worries, I want to hold you guys up as little as possible. I hopefully fixed that my deleting the result every time we pop. Let me know if the problem persists because of peek too, don't really know how that'll work. Also FYI, I updated the Object and String classes to add length to the string class and to make hash be virtual, as per a recent Piazza post.

**Comment by sbhornjr** [comment]
I'm gonna close this, so if you have an issue with the new Object/String implementation or another memory leak issue then just make another issue so it'll be easier for us to see it.
