### ISSUE TITLE
Remove fields from .h files

### ISSUE THREAD

**Issue by Danijj89** [arthurarmani/software-dev-steven-arthur-public#3]
Would it be possible to remove the fields from the header files as per: https://piazza.com/class/k51bluky59n2jr?cid=291 ?
We received the same request from a different team and I believe removing them would help to generalize the class better to work with other people's specs. Thanks

**Comment by sbhornjr** [comment]
Sorry for the late response, hope it wasn't too much of a hold up. I saw another post on piazza that said that "necessary" fields should be included in the spec and figured that at least the char* field would be considered necessary, but if you prefer we can definitely take them out. I'll do that now, it'll be ready in like a minute.
