### ISSUE TITLE
StringQueue implementation specs

### ISSUE THREAD

**Issue by Danijj89** [arthurarmani/software-dev-steven-arthur-public#4]
It seems from this piazza post https://piazza.com/class/k51bluky59n2jr?cid=341 that we would support for something on the line of "String s = queue.pop()" should be supported. I believe this is hinting on a StringQueue class. Could you provide specs and tests for such a class? Thanks!

**Comment by sbhornjr** [comment]
Yeah, I think you're right. At first I was thinking they were definitely hinting at having wrappers for each of the data types (i.e. float, int, and bool for the array), but now it seems like they're advocating for different classes for each type for each data structure. I'll get on this now and hope to finish soon but I'm in class so I'll let you know when it's good to go.

**Comment by sbhornjr** [comment]
Ok I added ObjectQueue and StringQueue classes, and updated the tests to deal with StringQueues
