### ISSUE TITLE
test-queue comprehensiveness

### ISSUE THREAD

**Issue by swindl** [arthurarmani/software-dev-steven-arthur-public#7]
Can 1 or 2 more tests that cover more edge cases be added to the test file?
Basically adding a large amount of strings or objects that make sure the circular functionality of our implementation is correct.

**Comment by sbhornjr** [comment]
So you just want a test that adds a bunch of strings to the queue (and then pops them?)? How many is a large amount?

**Comment by swindl** [comment]
Yes, not really interested in uniqueness so much as volume. So I would just loop through pushing and popping like a 1000.

**Comment by sbhornjr** [comment]
Ok, and by that do you mean pushing and then popping 1000 times, or pushing 1000 times and then popping 1000 times?

**Comment by swindl** [comment]
Pushing 1000 times and then popping 1000 times sounds good to me. So that size() == 0 at the end.

**Comment by sbhornjr** [comment]
Ok cool ill let you know when it's done.

**Comment by swindl** [comment]
Thanks!

**Comment by sbhornjr** [comment]
Alright I added the test, let me know if I made some off by one error in those loops or something like that or if that wasn't exactly what you were looking for.
